version: "3.8"

services:
  db:
    image: postgres:16.9-alpine
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/tmp/init.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_HOST: db
    ports:
      - "5432:5432"
    command: sh -c "while ! pg_isready -U postgres; do sleep 1; done; envsubst < /tmp/init.sql | psql -U postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U DB_USER -d DB_NAME" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_HOST: db
    env_file:
      - .env

volumes:
  db_data: